+ export HF_DATASETS_OFFLINE=0
+ HF_DATASETS_OFFLINE=0
+ export TRANSFORMERS_OFFLINE=0
+ TRANSFORMERS_OFFLINE=0
+ module load pytorch-gpu/py3/1.7.0
+ unset _mlshdbg
+ '[' 0 = 1 ']'
+ unset _mlre _mlIFS
+ '[' -n x ']'
+ _mlIFS=' 	
'
+ IFS=' '
+ for _mlv in ${MODULES_RUN_QUARANTINE:-}
+ '[' LD_LIBRARY_PATH = LD_LIBRARY_PATH -a LD_LIBRARY_PATH = LD_LIBRARY_PATH ']'
++ eval 'echo ${LD_LIBRARY_PATH+x}'
+++ echo x
+ '[' -n x ']'
++ eval 'echo ${LD_LIBRARY_PATH}'
+++ echo /gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
+ _mlre='LD_LIBRARY_PATH_modquar='\''/gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' '
+ _mlrv=MODULES_RUNENV_LD_LIBRARY_PATH
++ eval 'echo ${MODULES_RUNENV_LD_LIBRARY_PATH:-}'
+++ echo
+ _mlre='LD_LIBRARY_PATH_modquar='\''/gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' LD_LIBRARY_PATH='\'''\'' '
+ '[' -n 'LD_LIBRARY_PATH_modquar='\''/gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' LD_LIBRARY_PATH='\'''\'' ' ']'
++ eval 'LD_LIBRARY_PATH_modquar='\''/gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\''' 'LD_LIBRARY_PATH='\'''\''' /gpfslocalsup/spack_soft/tcl/8.6.8/gcc-4.8.5-5nqkfcnctewdheju62zvqbsonnzszr6m/bin/tclsh /gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/libexec/modulecmd.tcl bash '"$@"'
+++ LD_LIBRARY_PATH_modquar=/gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
+++ LD_LIBRARY_PATH=
+++ /gpfslocalsup/spack_soft/tcl/8.6.8/gcc-4.8.5-5nqkfcnctewdheju62zvqbsonnzszr6m/bin/tclsh /gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/libexec/modulecmd.tcl bash load pytorch-gpu/py3/1.7.0
+ eval
+ _mlstatus=0
+ '[' -n x ']'
+ IFS=' 	
'
+ unset _mlre _mlv _mlrv _mlIFS
+ '[' -n '' ']'
+ unset _mlshdbg
+ return 0
+ srun bash -c 'python process.py -src_lang zh -num_workers=8 -cutoff 30'
2022-03-05 08:41:18.161615: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2022-03-05 08:41:18.161644: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-05 08:41:19.865520: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsup/spack_soft/openmpi/4.0.2/gcc-8.3.1-ibnz44d4oyquf2axzzyh24i5h5xbihdw/lib:/gpfslocalsup/spack_soft/magma/2.5.3/gcc-8.3.1-54st4ebvspfanepxibzajjd4rbfv45r7/lib:/gpfslocalsys/intel/parallel_studio_xe_2020_update1_cluster_edition/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/gpfslocalsup/spack_soft/cudnn/7.6.5.32-10.2-linux-x64/gcc-8.3.1-udqxcfv5zksi3pjgukwililn5j27swka/lib64:/gpfslocalsup/spack_soft/nccl/2.6.4-1/gcc-8.3.1-stsc6mt6knjkz5cygoembh4daha2jmnm/lib:/gpfslocalsys/cuda/10.2/nvvm/lib64:/gpfslocalsys/cuda/10.2/extras/CUPTI/lib64:/gpfslocalsys/cuda/10.2/lib64:/gpfslocalsys/cuda/10.2/samples/common/lib/linux/x86_64:/gpfslocalsys/cuda/10.2/targets/x86_64-linux/lib:/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2022-03-05 08:41:19.865552: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-05 08:41:23,259 : MainProcess : INFO : ('multiprocess_ner ', None, ['zh'])
2022-03-05 08:41:26,445 : MainProcess : INFO : ('multiprocess_ner ', None, ['zh'])
2022-03-05 08:41:27,931 : MainProcess : INFO : Load pretrained SentenceTransformer: /linkhome/rech/genltc01/unm25jp/.cache/sentence-transformers/LaBSE
2022-03-05 08:41:30,991 : MainProcess : INFO : Load pretrained SentenceTransformer: /linkhome/rech/genltc01/unm25jp/.cache/sentence-transformers/LaBSE
2022-03-05 08:41:33,887 : MainProcess : INFO : Use pytorch device: cuda
2022-03-05 08:41:36,849 : MainProcess : INFO : Use pytorch device: cuda
Traceback (most recent call last):
  File "process.py", line 253, in <module>
    num_workers=num_workers)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 2616, in multiprocess_ner
    TextAugmentDeviceModel.initializer_all(src_langs=src_langs, target_langs=target_langs)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 132, in initializer_all
    available_device_model.initializer(src_langs=src_langs, target_langs=target_langs, aug_langs=aug_langs,device_id=device_id)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 164, in initializer
    tokenizer = AutoTokenizer.from_pretrained(model_name, model_max_length=512)
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 535, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1715, in from_pretrained
    user_agent=user_agent,
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 1854, in cached_path
    local_files_only=local_files_only,
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 2103, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
srun: error: r11i2n6: task 0: Exited with exit code 1
srun: Terminating job step 262832.0
Traceback (most recent call last):
  File "process.py", line 253, in <module>
    num_workers=num_workers)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 2616, in multiprocess_ner
    TextAugmentDeviceModel.initializer_all(src_langs=src_langs, target_langs=target_langs)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 132, in initializer_all
    available_device_model.initializer(src_langs=src_langs, target_langs=target_langs, aug_langs=aug_langs,device_id=device_id)
  File "/gpfsdswork/projects/rech/six/commun/PII/muliwai/text_augment.py", line 164, in initializer
    tokenizer = AutoTokenizer.from_pretrained(model_name, model_max_length=512)
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 535, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1715, in from_pretrained
    user_agent=user_agent,
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 1854, in cached_path
    local_files_only=local_files_only,
  File "/linkhome/rech/genltc01/unm25jp/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 2103, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
srun: error: r13i7n8: task 1: Exited with exit code 1
